ALTER TABLE recruitment_position
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

SELECT setval(pg_get_serial_sequence('recruitment_position', 'id'), COALESCE((SELECT MAX(id) FROM recruitment_position), 1), true);
