CREATE TABLE sys_role (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_code VARCHAR(40) NOT NULL UNIQUE,
    role_name VARCHAR(60) NOT NULL,
    description VARCHAR(255),
    status VARCHAR(20) NOT NULL DEFAULT 'ENABLED',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_role_status CHECK (status IN ('ENABLED', 'DISABLED'))
);

CREATE TABLE sys_department (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_code VARCHAR(40) NOT NULL UNIQUE,
    department_name VARCHAR(100) NOT NULL UNIQUE,
    description VARCHAR(255),
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_by BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_department_status CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

CREATE TABLE sys_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(80) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    real_name VARCHAR(80) NOT NULL,
    email VARCHAR(120),
    phone VARCHAR(30),
    department_id BIGINT REFERENCES sys_department(id),
    role_id BIGINT NOT NULL REFERENCES sys_role(id),
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    last_login_at TIMESTAMPTZ,
    created_by BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_user_status CHECK (status IN ('ACTIVE', 'LOCKED', 'DISABLED'))
);

ALTER TABLE sys_department
    ADD CONSTRAINT fk_department_created_by FOREIGN KEY (created_by) REFERENCES sys_user(id),
    ADD CONSTRAINT fk_department_updated_by FOREIGN KEY (updated_by) REFERENCES sys_user(id);
ALTER TABLE sys_user
    ADD CONSTRAINT fk_user_created_by FOREIGN KEY (created_by) REFERENCES sys_user(id),
    ADD CONSTRAINT fk_user_updated_by FOREIGN KEY (updated_by) REFERENCES sys_user(id);

CREATE TABLE job_position (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_id BIGINT NOT NULL REFERENCES sys_department(id),
    position_code VARCHAR(50) NOT NULL UNIQUE,
    position_name VARCHAR(100) NOT NULL,
    description TEXT,
    default_template_id BIGINT,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_by BIGINT NOT NULL REFERENCES sys_user(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT NOT NULL REFERENCES sys_user(id),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_position_department_name UNIQUE (department_id, position_name),
    CONSTRAINT ck_position_status CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

CREATE TABLE assessment_template (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_name VARCHAR(120) NOT NULL,
    position_id BIGINT NOT NULL REFERENCES job_position(id),
    owner_user_id BIGINT NOT NULL REFERENCES sys_user(id),
    status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    created_by BIGINT NOT NULL REFERENCES sys_user(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT NOT NULL REFERENCES sys_user(id),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_template_position_name UNIQUE (position_id, template_name),
    CONSTRAINT ck_template_status CHECK (status IN ('DRAFT', 'ACTIVE', 'DISABLED'))
);

ALTER TABLE job_position
    ADD CONSTRAINT fk_position_default_template FOREIGN KEY (default_template_id) REFERENCES assessment_template(id);

CREATE TABLE assessment_template_version (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_id BIGINT NOT NULL REFERENCES assessment_template(id),
    version_no INT NOT NULL,
    schema_json JSONB NOT NULL,
    version_status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    created_by BIGINT NOT NULL REFERENCES sys_user(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT NOT NULL REFERENCES sys_user(id),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    submitted_by BIGINT REFERENCES sys_user(id),
    submitted_at TIMESTAMPTZ,
    published_by BIGINT REFERENCES sys_user(id),
    published_at TIMESTAMPTZ,
    CONSTRAINT uq_template_version UNIQUE (template_id, version_no),
    CONSTRAINT ck_template_version_status CHECK (version_status IN ('DRAFT', 'PENDING', 'PUBLISHED', 'ARCHIVED'))
);

CREATE TABLE assessment_task (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_no VARCHAR(40) NOT NULL UNIQUE,
    candidate_name VARCHAR(80) NOT NULL,
    candidate_phone VARCHAR(30),
    candidate_email VARCHAR(120),
    candidate_source VARCHAR(50),
    phone_bound_at TIMESTAMPTZ,
    phone_verified_at TIMESTAMPTZ,
    position_id BIGINT NOT NULL REFERENCES job_position(id),
    hr_user_id BIGINT NOT NULL REFERENCES sys_user(id),
    template_version_id BIGINT NOT NULL REFERENCES assessment_template_version(id),
    token_hash VARCHAR(128) NOT NULL UNIQUE,
    deadline TIMESTAMPTZ NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'DRAFT',
    sent_at TIMESTAMPTZ,
    opened_at TIMESTAMPTZ,
    last_access_at TIMESTAMPTZ,
    draft_saved_at TIMESTAMPTZ,
    submitted_at TIMESTAMPTZ,
    review_started_at TIMESTAMPTZ,
    reviewed_at TIMESTAMPTZ,
    revoked_at TIMESTAMPTZ,
    archived_at TIMESTAMPTZ,
    version INT NOT NULL DEFAULT 0,
    created_by BIGINT NOT NULL REFERENCES sys_user(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_task_status CHECK (status IN ('DRAFT', 'SENT', 'OPENED', 'IN_PROGRESS', 'SUBMITTED', 'EXPIRED', 'REVOKED', 'REVIEWING', 'REVIEWED', 'ARCHIVED'))
);

CREATE TABLE assessment_answer (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id BIGINT NOT NULL REFERENCES assessment_task(id),
    question_id VARCHAR(80) NOT NULL,
    answer_json JSONB NOT NULL,
    draft_version INT NOT NULL DEFAULT 1,
    submitted_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_answer_task_question UNIQUE (task_id, question_id)
);

CREATE TABLE assessment_file (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id BIGINT NOT NULL REFERENCES assessment_task(id),
    question_id VARCHAR(80) NOT NULL,
    object_key VARCHAR(500) NOT NULL UNIQUE,
    file_name VARCHAR(255) NOT NULL,
    file_extension VARCHAR(30) NOT NULL,
    content_type VARCHAR(120) NOT NULL,
    size_bytes BIGINT NOT NULL,
    upload_status VARCHAR(20) NOT NULL DEFAULT 'UPLOADING',
    checksum VARCHAR(128),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMPTZ,
    deleted_at TIMESTAMPTZ,
    CONSTRAINT ck_file_size CHECK (size_bytes >= 0),
    CONSTRAINT ck_file_status CHECK (upload_status IN ('UPLOADING', 'COMPLETED', 'FAILED', 'DELETED'))
);

CREATE TABLE assessment_assignment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id BIGINT NOT NULL REFERENCES assessment_task(id),
    reviewer_user_id BIGINT NOT NULL REFERENCES sys_user(id),
    status VARCHAR(30) NOT NULL DEFAULT 'WAITING_CANDIDATE',
    assigned_by BIGINT NOT NULL REFERENCES sys_user(id),
    assigned_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    started_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    cancelled_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_assignment_task_reviewer UNIQUE (task_id, reviewer_user_id),
    CONSTRAINT ck_assignment_status CHECK (status IN ('WAITING_CANDIDATE', 'PENDING', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED'))
);

CREATE TABLE assessment_review (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assignment_id BIGINT NOT NULL UNIQUE REFERENCES assessment_assignment(id),
    conclusion VARCHAR(20) NOT NULL,
    reason TEXT,
    score NUMERIC(5,2),
    submitted_by BIGINT NOT NULL REFERENCES sys_user(id),
    submitted_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_review_conclusion CHECK (conclusion IN ('PASS', 'REJECTED', 'RESERVED')),
    CONSTRAINT ck_review_score CHECK (score IS NULL OR score BETWEEN 0 AND 100)
);

CREATE TABLE operation_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id BIGINT REFERENCES assessment_task(id),
    operator_type VARCHAR(20) NOT NULL,
    operator_id BIGINT,
    action VARCHAR(50) NOT NULL,
    from_status VARCHAR(30),
    to_status VARCHAR(30),
    detail_json JSONB,
    ip VARCHAR(64),
    user_agent VARCHAR(500),
    trace_id VARCHAR(64),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_log_operator_type CHECK (operator_type IN ('USER', 'CANDIDATE', 'SYSTEM'))
);

CREATE TABLE notification (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    receiver_user_id BIGINT NOT NULL REFERENCES sys_user(id),
    task_id BIGINT REFERENCES assessment_task(id),
    type VARCHAR(40) NOT NULL,
    title VARCHAR(200) NOT NULL,
    content TEXT NOT NULL,
    is_read BOOLEAN NOT NULL DEFAULT FALSE,
    read_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ
);

CREATE INDEX idx_department_status ON sys_department(status);
CREATE INDEX idx_user_department ON sys_user(department_id);
CREATE INDEX idx_user_role ON sys_user(role_id);
CREATE INDEX idx_user_status ON sys_user(status);
CREATE INDEX idx_position_department ON job_position(department_id);
CREATE INDEX idx_template_position ON assessment_template(position_id);
CREATE INDEX idx_template_version_status ON assessment_template_version(version_status);
CREATE INDEX idx_task_candidate_name ON assessment_task(candidate_name);
CREATE INDEX idx_task_candidate_phone ON assessment_task(candidate_phone);
CREATE INDEX idx_task_position ON assessment_task(position_id);
CREATE INDEX idx_task_hr ON assessment_task(hr_user_id);
CREATE INDEX idx_task_status ON assessment_task(status);
CREATE INDEX idx_task_deadline ON assessment_task(deadline);
CREATE INDEX idx_file_task ON assessment_file(task_id);
CREATE INDEX idx_assignment_reviewer ON assessment_assignment(reviewer_user_id, status);
CREATE INDEX idx_operation_task_created ON operation_log(task_id, created_at);
CREATE INDEX idx_notification_receiver_read ON notification(receiver_user_id, is_read);

INSERT INTO sys_role (role_code, role_name, description) VALUES
    ('ADMIN', '系统管理员', '系统配置及全部数据权限'),
    ('HR_MANAGER', 'HR主管', '招聘团队数据权限'),
    ('HR', '招聘专员', '本人负责的测评任务'),
    ('REVIEWER', '评估人员', '本人被分配的评估任务');

